import data from "./blur-data.json";

const previews: Record<string, string> = data;

/**
 * next/image props for a blurred preview of `src` (generated by scripts/images.mjs).
 * Server-side only: client components receive the data URL through props, so the full map never ships to the browser.
 */
export function blur(src: string): { placeholder?: "blur"; blurDataURL?: string } {
  const blurDataURL = previews[src];
  return blurDataURL ? { placeholder: "blur", blurDataURL } : {};
}

/** Attaches the cover's preview to a project before it is handed to a client component. */
export function withBlur<T extends { cover: { src: string } }>(project: T): T {
  return { ...project, cover: { ...project.cover, blurDataURL: blur(project.cover.src).blurDataURL } };
}
