import type { ImageLoaderProps } from "next/image";
import widths from "./image-widths.json";

/**
 * Static-export image loader: maps the width next/image asks for onto the files generated by scripts/images.mjs
 * (<name>-240.webp … <name>-2800.webp, one per width in image-widths.json). next.config.ts lists the same widths as
 * `deviceSizes`, so every <Image> gets an eight-entry srcset; `quality` is baked in at build time.
 * The master (<name>.webp) is the pipeline's source and is never served to a page.
 */
export default function imageLoader({ src, width }: ImageLoaderProps): string {
  if (!src.endsWith(".webp")) return src;
  const fit = widths.find((w) => width <= w) ?? widths[widths.length - 1];
  return src.replace(/\.webp$/, `-${fit}.webp`);
}
