import type { ImageLoaderProps } from "next/image";

/**
 * Static-export image loader: maps the width next/image asks for onto the variants
 * generated by scripts/images.mjs (<name>-700.webp, <name>-1400.webp, <name>.webp = 2800px master).
 * With deviceSizes [700, 1400, 2800] every <Image> gets a three-entry srcset; `quality` is baked in at build time.
 */
export default function imageLoader({ src, width }: ImageLoaderProps): string {
  if (!src.endsWith(".webp") || width > 1400) return src;
  return src.replace(/\.webp$/, width <= 700 ? "-700.webp" : "-1400.webp");
}
