import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Fully static site: every route is pre-rendered to HTML at build time (SEO-ready, host anywhere).
  output: "export",
  // Static hosts resolve /projects/ → /projects/index.html reliably.
  trailingSlash: true,
  images: {
    // No image server in a static export: variants are pre-generated by scripts/images.mjs
    // and picked per requested width by the loader, giving every <Image> a 700w / 1400w / 2800w srcset.
    loader: "custom",
    loaderFile: "./src/lib/image-loader.ts",
    deviceSizes: [700, 1400, 2800],
    imageSizes: [],
  },
  reactStrictMode: true,
  poweredByHeader: false,
};

export default nextConfig;
