import type { NextConfig } from "next";
import imageWidths from "./src/lib/image-widths.json";

const nextConfig: NextConfig = {
  // Fully static site: every route is pre-rendered to HTML at build time (SEO-ready, host anywhere).
  output: "export",
  // Static hosts resolve /projects/ → /projects/index.html reliably.
  trailingSlash: true,
  images: {
    // No image server in a static export: every size is pre-generated by scripts/images.mjs and picked per requested
    // width by the loader, giving every <Image> a 240w … 2800w srcset. The widths live in one file all three share.
    loader: "custom",
    loaderFile: "./src/lib/image-loader.ts",
    deviceSizes: imageWidths,
    imageSizes: [],
  },
  reactStrictMode: true,
  poweredByHeader: false,
};

export default nextConfig;
